// AUTO-GENERATED by packages/api/scripts/generate-releases.ts
// Regenerate after each release: yarn tsx scripts/generate-releases.ts

export interface Release {
  version: string;
  releasedAt: string;
}

export const RELEASES: readonly Release[] = [
  { version: "0.0.1", releasedAt: "2024-12-11" },
  { version: "0.0.2", releasedAt: "2025-01-06" },
  { version: "0.0.3", releasedAt: "2025-01-10" },
  { version: "0.0.4", releasedAt: "2025-01-14" },
  { version: "0.0.5", releasedAt: "2025-01-24" },
  { version: "0.0.6", releasedAt: "2025-01-31" },
  { version: "0.0.7", releasedAt: "2025-02-02" },
  { version: "0.0.8", releasedAt: "2025-02-09" },
  { version: "1.0.0", releasedAt: "2025-02-12" },
  { version: "1.0.1", releasedAt: "2025-03-01" },
  { version: "1.2.0", releasedAt: "2025-03-25" },
  { version: "2.0.0", releasedAt: "2025-04-03" },
  { version: "2.0.1", releasedAt: "2025-04-06" },
  { version: "2.0.2", releasedAt: "2025-04-13" },
  { version: "2.0.3", releasedAt: "2025-04-14" },
  { version: "2.0.4", releasedAt: "2025-05-01" },
  { version: "2.1.0", releasedAt: "2025-05-04" },
  { version: "2.1.1", releasedAt: "2025-11-05" },
  { version: "2.2.0", releasedAt: "2025-11-06" },
  { version: "2.2.1", releasedAt: "2025-11-13" },
  { version: "2.3.0", releasedAt: "2026-01-24" },
] as const;
