// AUTO-GENERATED by packages/api/scripts/generate-releases.ts
// Regenerate after each release: yarn tsx scripts/generate-releases.ts

export interface Release {
  version: string;
  releasedAt: string;
}

export const RELEASES: readonly Release[] = [
  { version: "1.0.0", releasedAt: "2025-02-12" },
  { version: "2.0.0", releasedAt: "2025-04-03" },
  { version: "3.0.0", releasedAt: "2026-04-18" },
] as const;
