/**
 * Per-mountain scrape pipeline, reusable across `scrape-one.ts` (single-shot)
 * and `scrape-batch.ts` (bulk driver). Owns the search → detail-loop → Gemini
 * rewrite → file-write sequence for one Target; the caller owns the Playwright
 * session and Gemini client so they can be shared across many targets.
 */
import { writeFileSync } from "fs";
import { resolve } from "path";

import {
  detectSummitsGeometric,
  type CatalogPeak,
} from "./detect-summits-geometric";
import {
  interceptCoordinatesDuringNav,
  tryFetchGpx,
} from "./fetch-coordinates";
import { jitteredDelay, openPage } from "./fetch-page";
import type { BrowserSession } from "./fetch-page";
import type { GeminiTextClient } from "./gemini";
import { loadAllMountains } from "./load-mountains";
import { parseSearchResults } from "./parse-search";
import { parseTrailDetail } from "./parse-trail";
import { rewriteDescriptions } from "./rewrite-descriptions";
import { rewriteTitles } from "./rewrite-titles";
import type { TrailDetail } from "./types";
import { validateTrails } from "./validate-trails";

export type Target = {
  slug: string;
  // Human-readable mountain name, used by Gemini when rewriting titles so the
  // model knows what each title refers to.
  name: string;
  // Free-form region string from the seed location column (e.g. "Baix Ebre,
  // Terra Alta"). Gemini uses it to spot wrong-region false positives.
  location: string;
  // Optional summit height. Gives Gemini another disambiguation signal —
  // helps it reject routes labeled with the right name but different peak.
  heightMeters?: number | null;
  query: string;
  bbox: { swLat: number; swLng: number; neLat: number; neLng: number };
};

export type ScrapeResult =
  | { status: "ok"; trails: TrailDetail[]; outPath: string }
  | { status: "no-results" }
  | { status: "error"; error: Error };

export const TOP_N = 5;

const buildSearchUrl = (t: Target): string => {
  const sw = `${t.bbox.swLat},${t.bbox.swLng}`;
  const ne = `${t.bbox.neLat},${t.bbox.neLng}`;
  const params = new URLSearchParams({
    sw,
    ne,
    q: t.query,
    // a=10 is Wikiloc's activity code for "Hiking". We also defensively filter
    // by URL slug downstream in parseSearchResults so non-hiking sneak-ins drop.
    a: "10",
    fitMapToTrails: "1",
    page: "1",
  });
  return `https://www.wikiloc.com/wikiloc/map.do?${params.toString()}`;
};

const serializeOutput = (target: Target, trails: TrailDetail[]): string => {
  const header = [
    "// Generated by packages/api/scripts/wikiloc — do not hand-edit.",
    `// Source query: ${JSON.stringify(target.query)} via Wikiloc map search.`,
    `// Scraped at: ${new Date().toISOString()}.`,
    "",
    'import type { MountainRoute } from "../route.types";',
    "",
  ].join("\n");
  const body = `export const trails: MountainRoute[] = ${JSON.stringify(trails, null, 2)};\n`;
  return `${header}${body}`;
};

/**
 * Scrape one mountain end-to-end. Returns `no-results` when the search comes
 * back empty (caller decides whether to retry with a wider bbox or skip).
 * Any thrown error from Wikiloc / network / Playwright propagates as
 * `{ status: "error" }` so the caller can decide whether to abort.
 */
export const scrapeMountain = async (params: {
  session: BrowserSession;
  gemini: GeminiTextClient;
  target: Target;
  outputDir: string;
  /** Logger prefix; defaults to the slug. Used to distinguish concurrent /
   *  batched runs in the console. */
  logPrefix?: string;
}): Promise<ScrapeResult> => {
  const { session, gemini, target, outputDir } = params;
  const prefix = params.logPrefix ?? target.slug;
  const log = (msg: string): void => console.log(`[${prefix}] ${msg}`);

  try {
    const searchUrl = buildSearchUrl(target);
    log(`search: ${searchUrl}`);
    const searchPage = await openPage(session, searchUrl);
    await searchPage
      .waitForLoadState("networkidle", { timeout: 30_000 })
      .catch(() => {});
    const entries = await parseSearchResults(searchPage, TOP_N);
    await searchPage.close();
    log(`found ${entries.length} trail link(s)`);
    if (entries.length === 0) return { status: "no-results" };

    const trails: TrailDetail[] = [];
    for (const [index, entry] of entries.entries()) {
      log(`(${index + 1}/${entries.length}) ${entry.url}`);
      await jitteredDelay(3_000, 2_000);
      const page = await session.context.newPage();
      try {
        const coordinates = await interceptCoordinatesDuringNav(
          page,
          entry.url,
        );
        const detail = await parseTrailDetail(page, entry.url);
        let coords = coordinates;
        if (!coords) {
          log("  intercept missed — trying GPX endpoint");
          coords = await tryFetchGpx(page, detail.externalId);
        }
        detail.coordinates = coords;
        log(
          `  parsed: ${detail.titleRaw.slice(0, 80)} — ${
            detail.distanceMeters !== null
              ? `${detail.distanceMeters}m`
              : "?distance"
          }, ${coords ? `${coords.length} coords` : "no coords"}`,
        );
        trails.push(detail);
      } finally {
        await page.close();
      }
    }

    // First Gemini pass: filter candidates that don't actually summit the
    // target mountain, drop near-duplicates. We accept down to 1 result —
    // a single valid trail is still useful, and rejecting noisy search hits
    // matters more than padding the count.
    log(`gemini: validating ${trails.length} candidate(s)`);
    const { kept, rejected } = await validateTrails({
      client: gemini,
      mountainName: target.name,
      mountainLocation: target.location,
      mountainHeight: target.heightMeters ?? null,
      trails,
    });
    for (const r of rejected) {
      log(`  rejected ${r.trail.externalId}: ${r.reason}`);
    }
    if (kept.length === 0) {
      log("gemini rejected every candidate — treating as no-results");
      return { status: "no-results" };
    }
    log(`gemini kept ${kept.length}/${trails.length}`);

    // Second Gemini pass: rewrite titles into en/ca/es for the kept set.
    log(`gemini: rewriting ${kept.length} title(s)`);
    const localizedById = await rewriteTitles({
      client: gemini,
      mountainName: target.name,
      trails: kept,
    });
    for (const trail of kept) {
      const localized = localizedById.get(trail.externalId);
      if (localized) {
        trail.title = localized;
        log(
          `  ${trail.externalId}: en="${localized.en}" / ca="${localized.ca}"`,
        );
      }
    }

    // Third Gemini pass: rewrite descriptions. Lean en/ca/es summaries of
    // the raw author prose so the screen has something concise and locale-
    // aware to show without copying the source verbatim. Failure here is
    // non-fatal — the descriptionRaw fallback in the app still works.
    log(`gemini: rewriting ${kept.length} description(s)`);
    try {
      const descriptionsById = await rewriteDescriptions({
        client: gemini,
        mountainName: target.name,
        trails: kept,
      });
      for (const trail of kept) {
        const localized = descriptionsById.get(trail.externalId);
        if (localized) trail.description = localized;
      }
    } catch (error) {
      log(
        `description rewrite failed (continuing with raw): ${
          error instanceof Error ? error.message : String(error)
        }`,
      );
    }

    // Geometric summit detection: for each route, find every catalogued
    // mountain whose coordinates the GPS track passes within ~200m of.
    // No LLM — coordinates are the ground truth.
    log(`detecting summits geometrically for ${kept.length} route(s)`);
    const catalog: CatalogPeak[] = loadAllMountains().map((m) => ({
      slug: m.slug,
      latitude: m.latitude,
      longitude: m.longitude,
    }));
    for (const trail of kept) {
      trail.mountainSlugs = detectSummitsGeometric(trail, target.slug, catalog);
    }

    const outPath = resolve(outputDir, `${target.slug}.ts`);
    writeFileSync(outPath, serializeOutput(target, kept), "utf8");
    log(`wrote ${outPath}`);
    // App data folder is rebuilt by rebuild-data.ts (new layout: deduped
    // routes + mountain→route-ids index). Don't call syncToApp here — its
    // per-mountain `<slug>.ts` barrel is the OLD layout and overwrites the
    // index.ts that route.api.ts depends on.
    return { status: "ok", trails: kept, outPath };
  } catch (error) {
    return {
      status: "error",
      error: error instanceof Error ? error : new Error(String(error)),
    };
  }
};
