import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "fs";
import { resolve } from "path";

// Path to the app-side data folder. Output files written by the scraper are
// also copied here so the running app picks them up the moment the file
// lands. We re-generate the index barrel after every copy so new mountains
// auto-register without touching `route.api.ts`.
const APP_DATA_DIR = resolve(
  __dirname,
  "../../../../app/domains/route/data",
);

/**
 * Copy the freshly-written `output/<slug>.ts` into `packages/app/domains/
 * route/data/<slug>.ts` and regenerate `data/index.ts`. The barrel exports
 * one big `ROUTES_BY_SLUG: Record<string, MountainRoute[]>` that the app
 * reads via `useRoutesForMountain(slug)`.
 *
 * Idempotent: safe to call again on the same slug.
 */
export const syncToApp = (params: {
  slug: string;
  scraperOutputPath: string;
}): void => {
  if (!existsSync(APP_DATA_DIR)) {
    mkdirSync(APP_DATA_DIR, { recursive: true });
  }
  const destPath = resolve(APP_DATA_DIR, `${params.slug}.ts`);
  copyFileSync(params.scraperOutputPath, destPath);
  regenerateIndex();
};

const INDEX_FILENAME = "index.ts";

const regenerateIndex = (): void => {
  // Enumerate every <slug>.ts in the data folder (ignoring index itself and
  // route.types). We sort so the generated file is deterministic across runs
  // — git diffs only show real changes.
  const entries = readdirSync(APP_DATA_DIR)
    .filter((f) => f.endsWith(".ts") && f !== INDEX_FILENAME)
    .sort();

  // Convert "pica-destats.ts" → ("picaDestatsTrails", "pica-destats"). Module
  // identifiers can't contain `-` so we camelCase the slug for the import
  // alias.
  const lines: string[] = [
    "// Generated by packages/api/scripts/wikiloc — do not hand-edit.",
    "// Re-runs every time the scraper writes a mountain's output file.",
    "",
  ];
  const importAliases: { alias: string; slug: string }[] = [];
  for (const fileName of entries) {
    const slug = fileName.slice(0, -".ts".length);
    const alias = slugToIdentifier(slug);
    importAliases.push({ alias, slug });
    lines.push(`import { trails as ${alias} } from "./${slug}";`);
  }
  lines.push("");
  lines.push('import type { MountainRoute } from "../route.types";');
  lines.push("");
  lines.push(
    "export const ROUTES_BY_SLUG: Record<string, MountainRoute[]> = {",
  );
  for (const { alias, slug } of importAliases) {
    lines.push(`  "${slug}": ${alias},`);
  }
  lines.push("};");
  lines.push("");

  writeFileSync(resolve(APP_DATA_DIR, INDEX_FILENAME), lines.join("\n"), "utf8");
};

// "pica-destats" → "picaDestatsTrails". Strips non-identifier chars; the
// `Trails` suffix avoids shadowing the slug variable in any consumer.
const slugToIdentifier = (slug: string): string => {
  const camel = slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, i) =>
      i === 0
        ? part.toLowerCase()
        : part[0].toUpperCase() + part.slice(1).toLowerCase(),
    )
    .join("");
  return `${camel}Trails`;
};
