services:
  postgres:
    image: postgres:15-alpine
    container_name: 100cims_local_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: 100cims_local_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
