/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/public/mountains/one": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicMountainsOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/mountains/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicMountainsAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/mountains/summits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicMountainsSummits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiPublicJoin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/hiscores/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicHiscoresAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/challenge/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicChallengeAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/user/one": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicUserOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/user/summits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicUserSummits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/user/user-profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicUserUser-profile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/plans/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicPlansAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/plans/one": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicPlansOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/public/plans/count-new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiPublicPlansCount-new"];
    put?: never;
    post: operations["postApiPublicPlansCount-new"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/user/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedUserMe"];
    put?: never;
    post: operations["postApiProtectedUserMe"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/user/summits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedUserSummits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/user/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedUserAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/user/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedUserDelete"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/user/suggestion": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedUserSuggestion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/mountain/summit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedMountainSummit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/summit/one": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedSummitOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/summit/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedSummitDelete"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/donors/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedDonorsAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/donors/current-month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedDonorsCurrent-month"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/donors/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedDonors"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansCreate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansUpdate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansDelete"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansJoin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansLeave"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/chat/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansChatRead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/chat/unread": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedPlansChatUnread"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/chat/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postApiProtectedPlansChatSend"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/chat/all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiProtectedPlansChatAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/protected/plans/chat/delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["deleteApiProtectedPlansChatDelete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getApiPublicMountainsOne: {
    parameters: {
      query: {
        mountainSlug: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            };
          };
        };
      };
    };
  };
  getApiPublicMountainsAll: {
    parameters: {
      query: {
        challengeId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              location: string;
              essential: boolean;
              height: string;
              latitude: string;
              longitude: string;
              imageUrl: (string | null) | null;
            }[];
          };
        };
      };
    };
  };
  getApiPublicMountainsSummits: {
    parameters: {
      query: {
        challengeId: string;
        mountainId?: (string | null) | null;
        limit?: (number | null) | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              summitId: string;
              mountainId: string;
              mountainSlug: string;
              summitImageUrl: string;
              summitedAt: string;
              createdAt: Record<string, never> | string | number;
              mountainName: string;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              summitId: string;
              mountainId: string;
              mountainSlug: string;
              summitImageUrl: string;
              summitedAt: string;
              createdAt: Record<string, never> | string | number;
              mountainName: string;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              summitId: string;
              mountainId: string;
              mountainSlug: string;
              summitImageUrl: string;
              summitedAt: string;
              createdAt: Record<string, never> | string | number;
              mountainName: string;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
        };
      };
    };
  };
  postApiPublicJoin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          provider: "apple" | "google";
          identityToken: string;
          firstName?: string;
          lastName?: string;
          locale?: string;
        };
        "multipart/form-data": {
          provider: "apple" | "google";
          identityToken: string;
          firstName?: string;
          lastName?: string;
          locale?: string;
        };
        "text/plain": {
          provider: "apple" | "google";
          identityToken: string;
          firstName?: string;
          lastName?: string;
          locale?: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
          "multipart/form-data": {
            success: boolean;
            message: string;
          };
          "text/plain": {
            success: boolean;
            message: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
          "multipart/form-data": {
            success: boolean;
            message: string;
          };
          "text/plain": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  getApiPublicHiscoresAll: {
    parameters: {
      query: {
        challengeId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              userId: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              summitsCount: string;
              uniquePeaksCount: string;
              essentialPeaksCount: string;
              totalScore: number;
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              userId: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              summitsCount: string;
              uniquePeaksCount: string;
              essentialPeaksCount: string;
              totalScore: number;
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              userId: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              summitsCount: string;
              uniquePeaksCount: string;
              essentialPeaksCount: string;
              totalScore: number;
            }[];
          };
        };
      };
    };
  };
  getApiPublicChallengeAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              country: string;
              totalMountains: string;
              totalEssentialMountains: string;
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              country: string;
              totalMountains: string;
              totalEssentialMountains: string;
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              name: string;
              slug: string;
              country: string;
              totalMountains: string;
              totalEssentialMountains: string;
            }[];
          };
        };
      };
    };
  };
  getApiPublicUserOne: {
    parameters: {
      query: {
        userId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
        };
      };
    };
  };
  getApiPublicUserSummits: {
    parameters: {
      query: {
        userId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitedValidated: boolean;
              summitedImageUrl: string;
              mountainName: string;
              mountainSlug: string;
              mountainImageUrl: (string | null) | null;
              mountainHeight: string;
              mountainEssential: boolean;
              participants: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitedValidated: boolean;
              summitedImageUrl: string;
              mountainName: string;
              mountainSlug: string;
              mountainImageUrl: (string | null) | null;
              mountainHeight: string;
              mountainEssential: boolean;
              participants: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitedValidated: boolean;
              summitedImageUrl: string;
              mountainName: string;
              mountainSlug: string;
              mountainImageUrl: (string | null) | null;
              mountainHeight: string;
              mountainEssential: boolean;
              participants: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            }[];
          };
        };
      };
    };
  };
  "getApiPublicUserUser-profile": {
    parameters: {
      query: {
        userId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              firstSummitDate: (string | null) | null;
              lastSummitDate: (string | null) | null;
              score: number;
              sharedUsers: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                score: number;
              }[];
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              firstSummitDate: (string | null) | null;
              lastSummitDate: (string | null) | null;
              score: number;
              sharedUsers: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                score: number;
              }[];
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              firstSummitDate: (string | null) | null;
              lastSummitDate: (string | null) | null;
              score: number;
              sharedUsers: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                score: number;
              }[];
            };
          };
        };
      };
    };
  };
  getApiPublicPlansAll: {
    parameters: {
      query?: {
        status?: string;
        limit?: number;
        creatorId?: string;
        userId?: string;
        sort?: string;
        challengeId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
              }[];
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
              }[];
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
              }[];
            }[];
          };
        };
      };
    };
  };
  getApiPublicPlansOne: {
    parameters: {
      query: {
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
                essential: boolean;
              }[];
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
                essential: boolean;
              }[];
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: string;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              users: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
                willBringDogs: (boolean | null) | null;
              }[];
              mountains: {
                id: string;
                name: string;
                slug: string;
                imageUrl: (string | null) | null;
                location: string;
                height: string;
                essential: boolean;
              }[];
            };
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
          "multipart/form-data": {
            success: boolean;
            message: string;
          };
          "text/plain": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  "getApiPublicPlansCount-new": {
    parameters: {
      query?: {
        userId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            count: number;
          };
          "multipart/form-data": {
            success: boolean;
            count: number;
          };
          "text/plain": {
            success: boolean;
            count: number;
          };
        };
      };
    };
  };
  "postApiPublicPlansCount-new": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          userId: string;
        };
        "multipart/form-data": {
          userId: string;
        };
        "text/plain": {
          userId: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
    };
  };
  getApiProtectedUserMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              email: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
              town: (string | null) | null;
              visibleOnHiscores: boolean;
              visibleOnPeopleSearch: boolean;
              locale: (string | null) | null;
              username: (string | null) | null;
            };
          };
        };
      };
    };
  };
  postApiProtectedUserMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          firstName?: string;
          lastName?: string;
          image?: string;
          town?: string;
          visibleOnHiscores?: boolean;
          visibleOnPeopleSearch?: boolean;
        };
        "multipart/form-data": {
          firstName?: string;
          lastName?: string;
          image?: string;
          town?: string;
          visibleOnHiscores?: boolean;
          visibleOnPeopleSearch?: boolean;
        };
        "text/plain": {
          firstName?: string;
          lastName?: string;
          image?: string;
          town?: string;
          visibleOnHiscores?: boolean;
          visibleOnPeopleSearch?: boolean;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  getApiProtectedUserSummits: {
    parameters: {
      query?: {
        challengeId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              score: number;
              uniquePeaksCount: number;
              essentialPeaksCount: number;
              summits: {
                summitId: string;
                summitedAt: string;
                summitedValidated: boolean;
                mountainName: string;
                mountainSlug: string;
                mountainImageUrl: (string | null) | null;
                mountainHeight: string;
                mountainEssential: boolean;
                score: number;
              }[];
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              score: number;
              uniquePeaksCount: number;
              essentialPeaksCount: number;
              summits: {
                summitId: string;
                summitedAt: string;
                summitedValidated: boolean;
                mountainName: string;
                mountainSlug: string;
                mountainImageUrl: (string | null) | null;
                mountainHeight: string;
                mountainEssential: boolean;
                score: number;
              }[];
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              score: number;
              uniquePeaksCount: number;
              essentialPeaksCount: number;
              summits: {
                summitId: string;
                summitedAt: string;
                summitedValidated: boolean;
                mountainName: string;
                mountainSlug: string;
                mountainImageUrl: (string | null) | null;
                mountainHeight: string;
                mountainEssential: boolean;
                score: number;
              }[];
            };
          };
        };
      };
    };
  };
  getApiProtectedUserAll: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              firstName: (string | null) | null;
              lastName: (string | null) | null;
              imageUrl: (string | null) | null;
            }[];
          };
        };
      };
    };
  };
  getApiProtectedUserDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  postApiProtectedUserSuggestion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          suggestion: string;
        };
        "multipart/form-data": {
          suggestion: string;
        };
        "text/plain": {
          suggestion: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
    };
  };
  postApiProtectedMountainSummit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          mountainId: string;
          usersId: string[];
          date: string;
          image: string;
        };
        "multipart/form-data": {
          mountainId: string;
          usersId: string[];
          date: string;
          image: string;
        };
        "text/plain": {
          mountainId: string;
          usersId: string[];
          date: string;
          image: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  getApiProtectedSummitOne: {
    parameters: {
      query: {
        summitId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitValidated: boolean;
              summitImageUrl: string;
              mountainId: string;
              mountainName: string;
              mountainSlug: string;
              mountainLocation: string;
              mountainEssential: boolean;
              mountainHeight: string;
              mountainLatitude: string;
              mountainLongitude: string;
              mountainImageUrl: (string | null) | null;
              users: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitValidated: boolean;
              summitImageUrl: string;
              mountainId: string;
              mountainName: string;
              mountainSlug: string;
              mountainLocation: string;
              mountainEssential: boolean;
              mountainHeight: string;
              mountainLatitude: string;
              mountainLongitude: string;
              mountainImageUrl: (string | null) | null;
              users: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              summitId: string;
              summitedAt: string;
              summitValidated: boolean;
              summitImageUrl: string;
              mountainId: string;
              mountainName: string;
              mountainSlug: string;
              mountainLocation: string;
              mountainEssential: boolean;
              mountainHeight: string;
              mountainLatitude: string;
              mountainLongitude: string;
              mountainImageUrl: (string | null) | null;
              users: {
                userId: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              }[];
            };
          };
        };
      };
    };
  };
  postApiProtectedSummitDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          summitId: string;
        };
        "multipart/form-data": {
          summitId: string;
        };
        "text/plain": {
          summitId: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
          "multipart/form-data": {
            success: boolean;
            message: string;
          };
          "text/plain": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  getApiProtectedDonorsAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              userId: string;
              userImageUrl: (string | null) | null;
              userFirstName: (string | null) | null;
              userLastName: (string | null) | null;
              totalDonation: string;
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              userId: string;
              userImageUrl: (string | null) | null;
              userFirstName: (string | null) | null;
              userLastName: (string | null) | null;
              totalDonation: string;
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              userId: string;
              userImageUrl: (string | null) | null;
              userFirstName: (string | null) | null;
              userLastName: (string | null) | null;
              totalDonation: string;
            }[];
          };
        };
      };
    };
  };
  "getApiProtectedDonorsCurrent-month": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              totalDonation: string;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              totalDonation: string;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              totalDonation: string;
            };
          };
        };
      };
    };
  };
  postApiProtectedDonors: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          quantity: string;
        };
        "multipart/form-data": {
          quantity: string;
        };
        "text/plain": {
          quantity: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
    };
  };
  postApiProtectedPlansCreate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          title: string;
          description: string;
          startDate?: string;
          mountainIds?: string[];
          challengeId?: string;
        };
        "multipart/form-data": {
          title: string;
          description: string;
          startDate?: string;
          mountainIds?: string[];
          challengeId?: string;
        };
        "text/plain": {
          title: string;
          description: string;
          startDate?: string;
          mountainIds?: string[];
          challengeId?: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
        };
      };
    };
  };
  postApiProtectedPlansUpdate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          id: string;
          title?: string;
          description?: string;
          imageUrl?: string;
          status?: string;
          routeUrl?: string;
          startDate?: string;
          mountainIds?: string[];
          userIds?: string[];
        };
        "multipart/form-data": {
          id: string;
          title?: string;
          description?: string;
          imageUrl?: string;
          status?: string;
          routeUrl?: string;
          startDate?: string;
          mountainIds?: string[];
          userIds?: string[];
        };
        "text/plain": {
          id: string;
          title?: string;
          description?: string;
          imageUrl?: string;
          status?: string;
          routeUrl?: string;
          startDate?: string;
          mountainIds?: string[];
          userIds?: string[];
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              title: string;
              description: (string | null) | null;
              imageUrl: (string | null) | null;
              speed: (string | null) | null;
              status: string;
              routeUrl: (string | null) | null;
              startDate: (string | null) | null;
              creatorId: string;
              createdAt: Record<string, never> | string | number;
              updatedAt: Record<string, never> | string | number;
              challengeId: (string | null) | null;
            };
          };
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  postApiProtectedPlansDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          id: string;
        };
        "multipart/form-data": {
          id: string;
        };
        "text/plain": {
          id: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string;
          };
          "multipart/form-data": {
            success: boolean;
            message: string;
          };
          "text/plain": {
            success: boolean;
            message: string;
          };
        };
      };
    };
  };
  postApiProtectedPlansJoin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          id: string;
        };
        "multipart/form-data": {
          id: string;
        };
        "text/plain": {
          id: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  postApiProtectedPlansLeave: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          id: string;
        };
        "multipart/form-data": {
          id: string;
        };
        "text/plain": {
          id: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
  postApiProtectedPlansChatRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          planId: string;
        };
        "multipart/form-data": {
          planId: string;
        };
        "text/plain": {
          planId: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
    };
  };
  getApiProtectedPlansChatUnread: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: string[];
          };
          "multipart/form-data": {
            success: boolean;
            message: string[];
          };
          "text/plain": {
            success: boolean;
            message: string[];
          };
        };
      };
    };
  };
  postApiProtectedPlansChatSend: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          planId: string;
          message: string;
        };
        "multipart/form-data": {
          planId: string;
          message: string;
        };
        "text/plain": {
          planId: string;
          message: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              userId: string;
              planId: string;
              message: string;
              createdAt: Record<string, never> | string | number;
            };
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              userId: string;
              planId: string;
              message: string;
              createdAt: Record<string, never> | string | number;
            };
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              userId: string;
              planId: string;
              message: string;
              createdAt: Record<string, never> | string | number;
            };
          };
        };
      };
    };
  };
  getApiProtectedPlansChatAll: {
    parameters: {
      query: {
        planId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
            message: {
              id: string;
              message: string;
              createdAt: Record<string, never> | string | number;
              user: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              };
            }[];
          };
          "multipart/form-data": {
            success: boolean;
            message: {
              id: string;
              message: string;
              createdAt: Record<string, never> | string | number;
              user: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              };
            }[];
          };
          "text/plain": {
            success: boolean;
            message: {
              id: string;
              message: string;
              createdAt: Record<string, never> | string | number;
              user: {
                id: string;
                firstName: (string | null) | null;
                lastName: (string | null) | null;
                imageUrl: (string | null) | null;
              };
            }[];
          };
        };
      };
    };
  };
  deleteApiProtectedPlansChatDelete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          messageId: string;
        };
        "multipart/form-data": {
          messageId: string;
        };
        "text/plain": {
          messageId: string;
        };
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            success: boolean;
          };
          "multipart/form-data": {
            success: boolean;
          };
          "text/plain": {
            success: boolean;
          };
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string | boolean;
          };
          "multipart/form-data": {
            error: string | boolean;
          };
          "text/plain": {
            error: string | boolean;
          };
        };
      };
    };
  };
}
