/**
 * Regenerate src/api/lib/releases.ts from git history.
 *
 * Walks the version-bump commits of the Expo config files (legacy `app.json`
 * at repo root, then `packages/app/app.json`, then `packages/app/app.config.ts`)
 * and emits one entry per distinct semver, dated to the commit that introduced
 * it. Run this once after a release if you forget to manually append.
 *
 *   yarn tsx scripts/generate-releases.ts
 *
 * Commit dates approximate the release: an EAS submit usually goes out within
 * a few hours of the version bump, but Apple/Google approval can lag 1-3 days.
 * For reference-line markers on the admin overview that's plenty precise.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const REPO_ROOT = resolve(__dirname, "../../..");
const OUT_PATH = join(
  __dirname,
  "..",
  "src",
  "api",
  "lib",
  "releases.ts",
);

const PATHS = ["app.json", "packages/app/app.json", "packages/app/app.config.ts"];

const VERSION_LINE_RE = /^\+\s*(?:"version":|version:)\s*"([^"]+)"/;
const COMMIT_DATE_RE = /^=COMMIT [0-9a-f]+ (\d{4}-\d{2}-\d{2})/;

const collectFromPath = (path: string): Map<string, string[]> => {
  const out = new Map<string, string[]>();
  let raw: string;
  try {
    raw = execSync(
      `git log --all --follow --pretty=format:"=COMMIT %H %ci" -p -- ${path}`,
      { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 50 * 1024 * 1024 },
    );
  } catch {
    return out;
  }

  let date = "";
  for (const line of raw.split("\n")) {
    const c = line.match(COMMIT_DATE_RE);
    if (c) {
      date = c[1];
      continue;
    }
    const v = line.match(VERSION_LINE_RE);
    if (v && date) {
      const version = v[1];
      const arr = out.get(version) ?? [];
      arr.push(date);
      out.set(version, arr);
    }
  }
  return out;
};

const semverKey = (v: string): [number, number, number] => {
  const [a, b, c] = v.split(".").map((n) => Number.parseInt(n, 10));
  return [a || 0, b || 0, c || 0];
};

const semverCmp = (a: string, b: string): number => {
  const [aa, ab, ac] = semverKey(a);
  const [ba, bb, bc] = semverKey(b);
  return aa - ba || ab - bb || ac - bc;
};

const allDates = new Map<string, Set<string>>();
for (const p of PATHS) {
  for (const [version, dates] of collectFromPath(p)) {
    const set = allDates.get(version) ?? new Set<string>();
    for (const d of dates) set.add(d);
    allDates.set(version, set);
  }
}

// Walk versions in semver order; for each, accept the earliest date that
// is >= the previously accepted version's date. This skips placeholder
// commits (e.g. an `app.json` initialised to "1.0.0" before the real "0.0.1"
// release).
const accepted: { version: string; releasedAt: string }[] = [];
let floor = "0000-00-00";
const orderedVersions = [...allDates.keys()].sort(semverCmp);
for (const version of orderedVersions) {
  const candidates = [...(allDates.get(version) ?? [])].sort();
  const date = candidates.find((d) => d >= floor);
  if (!date) continue;
  accepted.push({ version, releasedAt: date });
  floor = date;
}

// Collapse to one release per calendar month — keep the latest version
// shipped that month (most representative of "what users were on").
const byMonth = new Map<string, { version: string; releasedAt: string }>();
for (const r of accepted) {
  const month = r.releasedAt.slice(0, 7);
  const existing = byMonth.get(month);
  if (!existing || semverCmp(r.version, existing.version) > 0) {
    byMonth.set(month, r);
  }
}

const sorted = [...byMonth.values()].sort((a, b) =>
  semverCmp(a.version, b.version),
);

const lines = [
  "// AUTO-GENERATED by packages/api/scripts/generate-releases.ts",
  "// Regenerate after each release: yarn tsx scripts/generate-releases.ts",
  "",
  "export interface Release {",
  "  version: string;",
  "  releasedAt: string;",
  "}",
  "",
  "export const RELEASES: readonly Release[] = [",
  ...sorted.map(
    (r) =>
      `  { version: "${r.version}", releasedAt: "${r.releasedAt}" },`,
  ),
  "] as const;",
  "",
];

writeFileSync(OUT_PATH, lines.join("\n"));
console.log(`Wrote ${sorted.length} releases to ${OUT_PATH}`);
