services:
  postgres:
    image: postgres:17-alpine
    container_name: cims
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cims
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
