/**
 * Rebuild the app-side data folder from the scraper outputs + the Gemini-
 * generated _summits.json. The new layout treats routes as a shared catalog:
 *
 *   packages/app/domains/route/data/
 *     routes/<externalId>.ts        — one file per UNIQUE route
 *     mountain-routes.ts            — `slug → externalId[]` map
 *     index.ts                      — barrel exporting both
 *
 * vs the old per-mountain layout where multi-peak routes were duplicated
 * once per mountain they summit.
 *
 * Usage:
 *   yarn tsx packages/api/scripts/wikiloc/rebuild-data.ts
 *
 * Idempotent. Safe to re-run after every detect-summits update.
 */
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "fs";
import { resolve } from "path";

import type { TrailDetail } from "./lib/types";

const OUTPUT_DIR = resolve(__dirname, "output");
const SUMMITS_PATH = resolve(OUTPUT_DIR, "_summits.json");
const APP_DATA_DIR = resolve(__dirname, "../../../app/domains/route/data");
const APP_ROUTES_DIR = resolve(APP_DATA_DIR, "routes");

// Match the scraper output template. Tolerates whitespace at the file end so
// hand-edits don't break the parse.
const TRAILS_REGEX = /export const trails: MountainRoute\[\] = ([\s\S]+);\s*$/m;

const readTrailsFile = (path: string): TrailDetail[] => {
  const text = readFileSync(path, "utf8");
  const match = text.match(TRAILS_REGEX);
  if (!match) throw new Error(`Could not find trails array in ${path}`);
  return JSON.parse(match[1]) as TrailDetail[];
};

type SummitsFile = Record<string, string[]>;

const serializeRoute = (route: TrailDetail & { mountainSlugs: string[] }): string => [
  "// Generated by packages/api/scripts/wikiloc/rebuild-data.ts — do not hand-edit.",
  "",
  'import type { MountainRoute } from "../../route.types";',
  "",
  `export const route: MountainRoute = ${JSON.stringify(route, null, 2)};`,
  "",
].join("\n");

const serializeMountainRoutes = (
  map: Record<string, string[]>,
): string => {
  const lines = [
    "// Generated by packages/api/scripts/wikiloc/rebuild-data.ts — do not hand-edit.",
    "",
    "export const MOUNTAIN_TO_ROUTE_IDS: Record<string, string[]> = {",
  ];
  for (const slug of Object.keys(map).sort()) {
    const ids = map[slug];
    lines.push(`  "${slug}": ${JSON.stringify(ids)},`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
};

// Camel-case the route id for the import alias. Route ids are numeric strings
// like "226941977" so we just prefix with `r` to make them valid identifiers.
const idToAlias = (externalId: string): string => `r${externalId}`;

const serializeIndex = (externalIds: string[]): string => {
  const lines = [
    "// Generated by packages/api/scripts/wikiloc/rebuild-data.ts — do not hand-edit.",
    "// Re-runs after every scrape + summit-detection pass.",
    "",
  ];
  for (const id of externalIds) {
    lines.push(`import { route as ${idToAlias(id)} } from "./routes/${id}";`);
  }
  lines.push("");
  lines.push('import type { MountainRoute } from "../route.types";');
  lines.push("");
  lines.push(
    "export const ROUTES_BY_ID: Record<string, MountainRoute> = {",
  );
  for (const id of externalIds) {
    lines.push(`  "${id}": ${idToAlias(id)},`);
  }
  lines.push("};");
  lines.push("");
  lines.push('export { MOUNTAIN_TO_ROUTE_IDS } from "./mountain-routes";');
  lines.push("");
  return lines.join("\n");
};

const main = (): void => {
  const summits = JSON.parse(readFileSync(SUMMITS_PATH, "utf8")) as SummitsFile;

  // Walk every scraper output file and gather routes, deduping by externalId.
  // When the same route appears in multiple files (because it summits more
  // than one mountain), we trust whichever copy we see first — they're
  // identical except for trivial diffs from re-scraping over time.
  const outputs = readdirSync(OUTPUT_DIR)
    .filter((f) => f.endsWith(".ts"))
    .sort();
  const routesById = new Map<string, TrailDetail>();
  for (const fileName of outputs) {
    const trails = readTrailsFile(resolve(OUTPUT_DIR, fileName));
    for (const t of trails) {
      if (!routesById.has(t.externalId)) routesById.set(t.externalId, t);
    }
  }
  console.log(
    `[rebuild] ${routesById.size} unique routes across ${outputs.length} mountain files`,
  );

  // Build mountain→routes map from the _summits.json. Skip empty arrays
  // (routes that don't summit any catalogued peak — they're orphans, not
  // shown anywhere).
  const mountainToRoutes: Record<string, string[]> = {};
  let droppedNoSummit = 0;
  for (const route of routesById.values()) {
    const slugs = summits[route.externalId];
    if (!slugs) {
      console.warn(
        `[rebuild] no summit data for ${route.externalId}; run detect-summits.ts first`,
      );
      continue;
    }
    if (slugs.length === 0) {
      droppedNoSummit += 1;
      continue;
    }
    for (const slug of slugs) {
      if (!mountainToRoutes[slug]) mountainToRoutes[slug] = [];
      mountainToRoutes[slug].push(route.externalId);
    }
  }
  console.log(
    `[rebuild] ${droppedNoSummit} routes dropped (no summit) · ${Object.keys(mountainToRoutes).length} mountains with routes`,
  );

  // Wipe the app data folder and rewrite from scratch. Resilient to old per-
  // mountain `<slug>.ts` files lingering from the previous layout.
  rmSync(APP_DATA_DIR, { recursive: true, force: true });
  mkdirSync(APP_ROUTES_DIR, { recursive: true });

  // Only emit routes that actually summit something. Orphans stay in the
  // scraper output (so re-detection can revive them if the heuristic
  // changes) but don't get bundled into the app.
  const keptIds: string[] = [];
  for (const route of routesById.values()) {
    const slugs = summits[route.externalId];
    if (!slugs || slugs.length === 0) continue;
    const enriched = { ...route, mountainSlugs: slugs };
    writeFileSync(
      resolve(APP_ROUTES_DIR, `${route.externalId}.ts`),
      serializeRoute(enriched),
      "utf8",
    );
    keptIds.push(route.externalId);
  }
  keptIds.sort();

  writeFileSync(
    resolve(APP_DATA_DIR, "mountain-routes.ts"),
    serializeMountainRoutes(mountainToRoutes),
    "utf8",
  );
  writeFileSync(
    resolve(APP_DATA_DIR, "index.ts"),
    serializeIndex(keptIds),
    "utf8",
  );
  console.log(
    `[rebuild] wrote ${keptIds.length} route files + mountain-routes.ts + index.ts`,
  );
};

main();
