/**
 * Manual one-mountain Wikiloc scrape for human review.
 *
 * Run:
 *   yarn tsx packages/api/scripts/wikiloc/scrape-one.ts
 *
 * Writes a TypeScript file under scripts/wikiloc/output/<slug>.ts containing
 * the parsed top-5 trails for the configured mountain. No DB writes.
 *
 * After parsing, Gemini rewrites each trail's title into en/ca/es so the app
 * gets short, distinct, human-friendly route names. Requires GEMINI_API_KEY
 * in packages/api/.env.local.
 */
import { config as loadDotenv } from "dotenv";
import { writeFileSync } from "fs";
import { resolve } from "path";

import { z } from "zod";

// Match the convention in drizzle.config.ts — read .env.local explicitly so the
// script works no matter what CWD it's invoked from. Resolves relative to the
// api package root (two levels up from scripts/wikiloc/).
loadDotenv({ path: resolve(__dirname, "../../.env.local") });

import { createGeminiTextClient } from "./lib/gemini";
import {
  closeBrowser,
  jitteredDelay,
  openBrowser,
  openPage,
} from "./lib/fetch-page";
import {
  interceptCoordinatesDuringNav,
  tryFetchGpx,
} from "./lib/fetch-coordinates";
import { parseSearchResults } from "./lib/parse-search";
import { parseTrailDetail } from "./lib/parse-trail";
import { rewriteTitles } from "./lib/rewrite-titles";
import type { TrailDetail } from "./lib/types";

const NonEmptyString = z.string().min(1);
const EnvSchema = z.object({
  GEMINI_API_KEY: NonEmptyString,
  GEMINI_MODEL: NonEmptyString.default("gemini-2.5-flash"),
});

type Target = {
  slug: string;
  // Human-readable mountain name, used by Gemini when rewriting titles so the
  // model knows what to lead each title with.
  name: string;
  query: string;
  bbox: { swLat: number; swLng: number; neLat: number; neLng: number };
};

const TARGET: Target = {
  // Match the DB slug exactly (see packages/api/src/db/drizzle/0001_seed-data.sql).
  slug: "pica-destats",
  name: "Pica d'Estats",
  query: "pica d'estats",
  // ~20km box around 42.6663, 1.3996
  bbox: { swLat: 42.50, swLng: 1.20, neLat: 42.83, neLng: 1.60 },
};

const TOP_N = 5;

const buildSearchUrl = (t: Target): string => {
  const sw = `${t.bbox.swLat},${t.bbox.swLng}`;
  const ne = `${t.bbox.neLat},${t.bbox.neLng}`;
  const params = new URLSearchParams({
    sw,
    ne,
    q: t.query,
    // a=10 is Wikiloc's activity code for "Hiking". We also defensively filter
    // by URL slug downstream in parseSearchResults so non-hiking sneak-ins drop.
    a: "10",
    fitMapToTrails: "1",
    page: "1",
  });
  return `https://www.wikiloc.com/wikiloc/map.do?${params.toString()}`;
};

const serializeOutput = (
  target: Target,
  trails: TrailDetail[],
): string => {
  // The output file is copied verbatim into
  // packages/app/domains/route/data/<slug>.ts, so emit the import path the
  // app expects (../route.types). The TrailDetail type and the app-side
  // MountainRoute share the same shape.
  const header = [
    "// Generated by packages/api/scripts/wikiloc/scrape-one.ts — do not hand-edit.",
    `// Source query: ${JSON.stringify(target.query)} via Wikiloc map search.`,
    `// Scraped at: ${new Date().toISOString()}.`,
    "",
    'import type { MountainRoute } from "../route.types";',
    "",
  ].join("\n");
  const body = `export const trails: MountainRoute[] = ${JSON.stringify(trails, null, 2)};\n`;
  return `${header}${body}`;
};

const main = async (): Promise<void> => {
  const session = await openBrowser();
  try {
    const searchUrl = buildSearchUrl(TARGET);
    console.log(`[wikiloc] search: ${searchUrl}`);
    const searchPage = await openPage(session, searchUrl);
    // Wikiloc lazy-loads cards; give it a moment to settle.
    await searchPage.waitForLoadState("networkidle", { timeout: 30_000 }).catch(() => {});
    const entries = await parseSearchResults(searchPage, TOP_N);
    await searchPage.close();
    console.log(`[wikiloc] found ${entries.length} trail link(s)`);
    if (entries.length === 0) {
      throw new Error("No trails found — bbox / query may need tightening");
    }

    const trails: TrailDetail[] = [];
    for (const [index, entry] of entries.entries()) {
      console.log(
        `[wikiloc] (${index + 1}/${entries.length}) ${entry.url}`,
      );
      await jitteredDelay(3_000, 2_000);
      const page = await session.context.newPage();
      try {
        const coordinates = await interceptCoordinatesDuringNav(page, entry.url);
        const detail = await parseTrailDetail(page, entry.url);
        let coords = coordinates;
        if (!coords) {
          console.log(`[wikiloc]   intercept missed — trying GPX endpoint`);
          coords = await tryFetchGpx(page, detail.externalId);
        }
        detail.coordinates = coords;
        console.log(
          `[wikiloc]   parsed: ${detail.titleRaw} — ${
            detail.distanceMeters ? `${detail.distanceMeters}m` : "?distance"
          }, ${coords ? `${coords.length} coords` : "no coords"}`,
        );
        trails.push(detail);
      } finally {
        await page.close();
      }
    }

    // Gemini rewrite: one batched call covering all 5 trails so it can produce
    // titles that are mutually distinct.
    const env = EnvSchema.parse(process.env);
    const gemini = createGeminiTextClient({
      apiKey: env.GEMINI_API_KEY,
      model: env.GEMINI_MODEL,
    });
    console.log(`[gemini] rewriting ${trails.length} titles (${env.GEMINI_MODEL})`);
    const localizedById = await rewriteTitles({
      client: gemini,
      mountainName: TARGET.name,
      trails,
    });
    for (const trail of trails) {
      const localized = localizedById.get(trail.externalId);
      if (localized) {
        trail.title = localized;
        console.log(
          `[gemini]   ${trail.externalId}: en="${localized.en}" ca="${localized.ca}"`,
        );
      }
    }

    const outPath = resolve(
      __dirname,
      "output",
      `${TARGET.slug}.ts`,
    );
    writeFileSync(outPath, serializeOutput(TARGET, trails), "utf8");
    console.log(`[wikiloc] wrote ${outPath}`);
  } finally {
    await closeBrowser(session);
  }
};

void main().catch((error) => {
  console.error("[wikiloc] failed:", error);
  process.exit(1);
});
