-- Second-pass Munro image backfill: 27 Munros via Commons categories.
-- Source filenames (geograph.org.uk etc.) are in inline comments.
-- 34 Munros (ambiguous/disambiguated names) still NULL — see .munros-no-image.txt.

UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/ben-more-01c.jpg' WHERE slug = 'ben-more-01c'; -- from File:A snow-covered Ben More - geograph.org.uk - 1866108.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-eibhinn.jpg' WHERE slug = 'beinn-eibhinn'; -- from File:Aonach Beag and Beinn Eibhinn - geograph.org.uk - 1719545.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/an-socach-12b.jpg' WHERE slug = 'an-socach-12b'; -- from File:An Riabhachan from the east ridge of An Socach - geograph.org.uk - 1130867.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-fhuar-thuill.jpg' WHERE slug = 'sgurr-fhuar-thuill'; -- from File:A cold hole indeed! - geograph.org.uk - 1596970.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-an-t-sagairt-mor.jpg' WHERE slug = 'carn-an-t-sagairt-mor'; -- from File:Cairn Bannoch - geograph.org.uk - 109829.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-an-righ.jpg' WHERE slug = 'carn-an-righ'; -- from File:Beinn Iutharn Mhòr from the Màm na Carn - Carn an Righ col - geograph.org.uk - 1228268.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-an-tuirc.jpg' WHERE slug = 'carn-an-tuirc'; -- from File:Cairn on Carn an Tuirc - geograph.org.uk - 603819.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-an-lochain.jpg' WHERE slug = 'sgurr-an-lochain'; -- from File:Approach to the summit of Sgùrr an Lochain - geograph.org.uk - 4113143.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/a-chailleach-14b.jpg' WHERE slug = 'a-chailleach-14b'; -- from File:A' Chailleach - geograph.org.uk - 1071415.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-na-ruaidhe.jpg' WHERE slug = 'sgurr-na-ruaidhe'; -- from File:Bealach nam Botaichean and Carn nan Gobhar - geograph.org.uk - 428289.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/creag-leacach.jpg' WHERE slug = 'creag-leacach'; -- from File:Boundary wall - geograph.org.uk - 41450.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/druim-shionnach.jpg' WHERE slug = 'druim-shionnach'; -- from File:Creag a' Mhàim and Druim Shionnach - geograph.org.uk - 1837230.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/mullach-na-dheiragain.jpg' WHERE slug = 'mullach-na-dheiragain'; -- from File:A Prized Summit - geograph.org.uk - 8044032.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/maol-chinn-dearg.jpg' WHERE slug = 'maol-chinn-dearg'; -- from File:Descending Druim nan Eirecheanach - geograph.org.uk - 948414.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-nan-ceapraichean.jpg' WHERE slug = 'meall-nan-ceapraichean'; -- from File:Bealach between Beinn Dearg and Meall nan Ceapraichean - geograph.org.uk - 883913.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/ben-more-17e.jpg' WHERE slug = 'ben-more-17e'; -- from File:A snow-covered Ben More - geograph.org.uk - 1866108.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/tolmount.jpg' WHERE slug = 'tolmount'; -- from File:Crow Craigies during the Eastern Cairngorm Challenge. - geograph.org.uk - 176103.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-ghluasaid.jpg' WHERE slug = 'carn-ghluasaid'; -- from File:An Cruachan - geograph.org.uk - 1721882.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-liath-mhor-fannaich.jpg' WHERE slug = 'beinn-liath-mhor-fannaich'; -- from File:Beinn Liath Mhòr Fannaich - geograph.org.uk - 1070736.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-gorm.jpg' WHERE slug = 'meall-gorm'; -- from File:Broad ridge near Meall Gorm - geograph.org.uk - 2720743.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/an-socach-06b.jpg' WHERE slug = 'an-socach-06b'; -- from File:An Riabhachan from the east ridge of An Socach - geograph.org.uk - 1130867.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-bhreac.jpg' WHERE slug = 'beinn-bhreac'; -- from File:Ben Lomond from Beinn Bhreac.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/a-chailleach-09b.jpg' WHERE slug = 'a-chailleach-09b'; -- from File:A' Chailleach - geograph.org.uk - 1071415.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/eididh-nan-clach-geala.jpg' WHERE slug = 'eididh-nan-clach-geala'; -- from File:Col between Eididh nan Clach Geala and Meall nan Ceapraichean - geograph.org.uk - 931034.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/creag-pitridh.jpg' WHERE slug = 'creag-pitridh'; -- from File:Bridge, Lochan na h-Earba - geograph.org.uk - 307169.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/an-coileachan.jpg' WHERE slug = 'an-coileachan'; -- from File:Approaching the summit of An Coileachan - geograph.org.uk - 2720748.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/an-socach-11a.jpg' WHERE slug = 'an-socach-11a'; -- from File:An Riabhachan from the east ridge of An Socach - geograph.org.uk - 1130867.jpg
