-- Third-pass Munro image backfill: 32 Munros resolved via Commons opensearch scoring + hand-curated mappings.
-- 2 Munros left NULL: beinn-dearg-06a (Atholl) and stob-daimh (Cruachan ridge) — Commons has no correct category.

-- Disambiguator pass (25 Munros):
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-a-chaorainn-08b.jpg' WHERE slug = 'beinn-a-chaorainn-08b'; -- from Category:Beinn a' Chaorainn, Cairngorms / File:Cairn on Beinn a' Chaorainn - geograph.org.uk - 4034823.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-a-ghlo-carn-nan-gabhar.jpg' WHERE slug = 'beinn-a-ghlo-carn-nan-gabhar'; -- from Category:Beinn a' Ghlò / File:Approach to Carn Liath - geograph.org.uk - 2382467.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-fhionnlaidh-03b.jpg' WHERE slug = 'beinn-fhionnlaidh-03b'; -- from Category:Beinn Fhionnlaidh, Argyll and Bute / File:Allt Ceitlein - geograph.org.uk - 241324.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/ben-vorlich-01d.jpg' WHERE slug = 'ben-vorlich-01d'; -- from Category:Ben Vorlich, Argyll and Bute / File:20091108 Lomond Ben Vorlich to Inverkip.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-dearg-04b-1.jpg' WHERE slug = 'carn-dearg-04b-1'; -- from Category:Càrn Dearg (Loch Ossian) / File:Across Coire Odhar Beag on Carn Dearg - geograph.org.uk - 5589197.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-dearg-09b.jpg' WHERE slug = 'carn-dearg-09b'; -- from Category:Càrn Dearg (Monadh Liath) / File:A fine way up onto the Carn Dearg Ridge - geograph.org.uk - 832188.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-nan-gobhar-12b.jpg' WHERE slug = 'carn-nan-gobhar-12b'; -- from Category:Càrn nan Gobhar (Strathfarrar) / File:Bealach nam Botaichean and Carn nan Gobhar - geograph.org.uk - 428289.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-sgulain.jpg' WHERE slug = 'carn-sgulain'; -- from Category:Càrn Sgùlain / File:Carn Sgulain , Munro No 271 - geograph.org.uk - 252638.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/creag-a-mhaim.jpg' WHERE slug = 'creag-a-mhaim'; -- from Category:Creag a' Mhàim / File:01 Llac Cluanie (Loch Cluanaidh), al fons els cims nevats del Creag a' Mhàim.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/geal-charn-05a.jpg' WHERE slug = 'geal-charn-05a'; -- from Category:Geal-Chàrn (Drumochter) / File:A'Mharconaich - geograph.org.uk - 333796.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/geal-charn-09b.jpg' WHERE slug = 'geal-charn-09b'; -- from Category:Geal Chàrn (Monadh Liath) / File:Battling the snow , SW ridge Geal Charn - geograph.org.uk - 129277.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-a-choire-leith.jpg' WHERE slug = 'meall-a-choire-leith'; -- from Category:Meall a' Choire Lèith / File:Ben Lawers - geograph.org.uk - 67638.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-buidhe-02a.jpg' WHERE slug = 'meall-buidhe-02a'; -- from Category:Meall Buidhe (Glen Lyon) / File:Ascending Meall Buidhe - geograph.org.uk - 2505205.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-buidhe-10b.jpg' WHERE slug = 'meall-buidhe-10b'; -- from Category:Meall Buidhe (Knoydart) / File:Camp in Gleann Meadail. - geograph.org.uk - 14675.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-garbh-02a.jpg' WHERE slug = 'meall-garbh-02a'; -- from Category:Meall Garbh (Lawers) / File:An Stuc and Meall Garbh - geograph.org.uk - 2898374.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/meall-garbh-02b.jpg' WHERE slug = 'meall-garbh-02b'; -- from Category:Meall Garbh (Lawers) / File:An Stuc and Meall Garbh - geograph.org.uk - 2898374.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sail-chaorainn.jpg' WHERE slug = 'sail-chaorainn'; -- from Category:Sàil Chaorainn / File:An Elric from Bealach an Amais - geograph.org.uk - 1257396.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-ban.jpg' WHERE slug = 'sgurr-ban'; -- from Category:Sgùrr Bàn / File:Boulderfield on Sgurr Ban - geograph.org.uk - 1256911.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-mor-10b.jpg' WHERE slug = 'sgurr-mor-10b'; -- from Category:Sgùrr Mòr (Fannichs) / File:At the summit cairn of Sgurr Mor - geograph.org.uk - 2211724.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-nan-coireachan-10b.jpg' WHERE slug = 'sgurr-nan-coireachan-10b'; -- from Category:Sgùrr nan Coireachan (Glen Dessary) / File:Allt Coire nan Uth - geograph.org.uk - 1248065.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/sgurr-nan-coireachan-10d.jpg' WHERE slug = 'sgurr-nan-coireachan-10d'; -- from Category:Sgùrr nan Coireachan (Glen Dessary) / File:Allt Coire nan Uth - geograph.org.uk - 1248065.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/stob-ban-04a-1.jpg' WHERE slug = 'stob-ban-04a-1'; -- from Category:Stob Bàn (Mamores) / File:Autumn cloud inversion on Stob Ban - geograph.org.uk - 2235267.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/stob-ban-04a-2.jpg' WHERE slug = 'stob-ban-04a-2'; -- from Category:Stob Bàn (Mamores) / File:Autumn cloud inversion on Stob Ban - geograph.org.uk - 2235267.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/stob-coire-sgriodain.jpg' WHERE slug = 'stob-coire-sgriodain'; -- from Category:Stob Coire Sgrìodain / File:Ascending Stob Coire Sgriodain - geograph.org.uk - 835932.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/tom-buidhe.jpg' WHERE slug = 'tom-buidhe'; -- from Category:Tom Buidhe, Angus / File:The path to the summit of Tom Buidhe. - geograph.org.uk - 412381.jpg

-- Hand-curated pass (7 Munros):
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-a-chaorainn-09c.jpg' WHERE slug = 'beinn-a-chaorainn-09c'; -- from Category:Beinn a' Chaorainn, Glen Spean / File:An Cearcallach - geograph.org.uk - 1654544.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-bhuidhe.jpg' WHERE slug = 'beinn-bhuidhe'; -- from Category:Beinn Bhuidhe, Glen Fyne / File:Beinn Bhuidhe - geograph.org.uk - 1247806.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-dearg-15a.jpg' WHERE slug = 'beinn-dearg-15a'; -- from Category:Beinn Dearg, Ullapool / File:A view of Beinn Dearg - geograph.org.uk - 7148682.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/beinn-fhionnlaidh-11a.jpg' WHERE slug = 'beinn-fhionnlaidh-11a'; -- from Category:Beinn Fhionnlaidh, Mullardoch / File:A welcome drink. - geograph.org.uk - 121373.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/ben-vorlich-01b.jpg' WHERE slug = 'ben-vorlich-01b'; -- from Category:Ben Vorlich (Loch Earn) / File:Approaching the summit of Ben Vorlich - geograph.org.uk - 3812037.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/carn-dearg-04b-2.jpg' WHERE slug = 'carn-dearg-04b-2'; -- from Category:Càrn Dearg (Ben Alder) / File:A view towards Carn Dearg - geograph.org.uk - 4477300.jpg
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/geal-charn-04b-2.jpg' WHERE slug = 'geal-charn-04b-2'; -- from Category:Geal Chàrn (Ben Alder) / File:An Lairig - geograph.org.uk - 1602033.jpg
