-- Picos de Europa: 33 images from user-reviewed Bing Image picks.
-- Each was verified against 4 candidates in /tmp/picos-review.html.

UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-las-minas-del-carbon.jpg' WHERE slug = 'torre-de-las-minas-del-carbon'; -- from https://cantur.com/2013/07/23/5-rutas-para-recorrer-los-picos-de-europa/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-coello.jpg' WHERE slug = 'torre-de-coello'; -- from https://www.pinterest.com/pin/parques-nacionales-picos-de-europa-la-torre-del-friero-desde-las-colladinas-camino-de-collado-jermoso-national-parks-picos-de-europa-la-torre-del-friero--320951910917337243/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/los-campanarios-ii.jpg' WHERE slug = 'los-campanarios-ii'; -- from https://telojuropormisbotas.blogspot.com/2015/12/los-campanarios-picos-de-santa-ana.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/los-campanarios-i.jpg' WHERE slug = 'los-campanarios-i'; -- from https://telojuropormisbotas.blogspot.com/2015/12/los-campanarios-picos-de-santa-ana.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/los-campanarios-iii.jpg' WHERE slug = 'los-campanarios-iii'; -- from https://cantur.com/2013/07/23/5-rutas-para-recorrer-los-picos-de-europa/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/los-campanarios-iv.jpg' WHERE slug = 'los-campanarios-iv'; -- from https://telojuropormisbotas.blogspot.com/2015/12/los-campanarios-picos-de-santa-ana.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-labrouche.jpg' WHERE slug = 'torre-de-labrouche'; -- from http://www.porpicos.com/ruta.84.torre.blanca.picos.europa.htm
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/pico-de-boada.jpg' WHERE slug = 'pico-de-boada'; -- from https://evaenolyjose.blogspot.com/2017/08/pico-boada-macizo-central-picos-de.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-las-coteras-rojas.jpg' WHERE slug = 'torre-de-las-coteras-rojas'; -- from https://cumbres-amazastur.blogspot.com/2010/08/torre-de-las-coteras-rojas.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-delgado-ubeda.jpg' WHERE slug = 'torre-de-delgado-ubeda'; -- from http://www.porpicos.com/ruta.84.torre.blanca.picos.europa.htm
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-diego-mella.jpg' WHERE slug = 'torre-diego-mella'; -- from https://es.pinterest.com/pin/refugio-diego-mella-picos-de-europa--300896818833754693/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-del-oso.jpg' WHERE slug = 'torre-del-oso'; -- from https://www.cotoyapindia.com/2020/07/ruta-torre-del-oso-picos-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/aguja-jose-de-prado.jpg' WHERE slug = 'aguja-jose-de-prado'; -- from https://todocazos.blogspot.com/2009/09/aguja-bustamante-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-la-celada.jpg' WHERE slug = 'torre-de-la-celada'; -- from http://www.porpicos.com/ruta.84.torre.blanca.picos.europa.htm
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-la-horcada.jpg' WHERE slug = 'torre-de-la-horcada'; -- from https://www.cotoyapindia.com/2020/09/ruta-torre-enmedio-horcada-picos-.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-del-torco.jpg' WHERE slug = 'torre-del-torco'; -- from http://www.porpicos.com/ruta.84.torre.blanca.picos.europa.htm
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-las-colladetas.jpg' WHERE slug = 'torre-de-las-colladetas'; -- from http://www.porpicos.com/ruta.84.torre.blanca.picos.europa.htm
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/tiros-de-santiago.jpg' WHERE slug = 'tiros-de-santiago'; -- from https://www.laguiavial.com/es/ruta-de-los-picos-de-europa/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-cebolleda-iii.jpg' WHERE slug = 'torre-de-cebolleda-iii'; -- from https://viajocomoquiero.com/parque-natural-picos-de-europa-2/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/neveron-del-albo.jpg' WHERE slug = 'neveron-del-albo'; -- from https://penasarriba.es/que-hacer-picos-de-europa/planes-ninos-familia-picos-de-europa/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/pico-del-albo.jpg' WHERE slug = 'pico-del-albo'; -- from https://viaturi.com/picos-mas-altos-europa/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/aguja-alpino.jpg' WHERE slug = 'aguja-alpino'; -- from https://todocazos.blogspot.com/2009/09/aguja-bustamante-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/aguja-de-juan-menendez.jpg' WHERE slug = 'aguja-de-juan-menendez'; -- from https://todocazos.blogspot.com/2009/09/aguja-bustamante-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/aguja-cimadevilla.jpg' WHERE slug = 'aguja-cimadevilla'; -- from https://todocazos.blogspot.com/2009/09/aguja-bustamante-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/aguja-jovellanos.jpg' WHERE slug = 'aguja-jovellanos'; -- from https://todocazos.blogspot.com/2009/09/aguja-bustamante-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-del-carnizoso.jpg' WHERE slug = 'torre-del-carnizoso'; -- from https://www.cotoyapindia.com/2020/07/ruta-torre-del-oso-picos-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-las-tres-marias-i.jpg' WHERE slug = 'torre-de-las-tres-marias-i'; -- from https://www.cotoyapindia.com/2019/08/tres-marias-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-cebolleda-ii.jpg' WHERE slug = 'torre-de-cebolleda-ii'; -- from https://geluni.blogspot.com/2012/10/picos-de-europa-ii.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torres-areneras.jpg' WHERE slug = 'torres-areneras'; -- from https://xistras.blogspot.com/2023/10/torres-areneras.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/torre-de-las-tres-marias-ii.jpg' WHERE slug = 'torre-de-las-tres-marias-ii'; -- from https://www.cotoyapindia.com/2019/08/tres-marias-picos-de-europa.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/porro-del-torco.jpg' WHERE slug = 'porro-del-torco'; -- from https://www.turismodeobservacion.com/foto/picos-de-europa/122331/
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/cuchalon-de-villasobrada.jpg' WHERE slug = 'cuchalon-de-villasobrada'; -- from https://imanol-zubero.blogspot.com/2023/07/picos-de-europa-ii.html
UPDATE mountain SET image_url = 'https://josepvidal-public-dev-bucket.s3.eu-west-3.amazonaws.com/100cims/mountain/profile/cueto-albo.jpg' WHERE slug = 'cueto-albo'; -- from https://alobouzo.blogspot.com/2018/07/cueto-tejao-picos-de-europa.html
