export type User = {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  imageUrl: string | null;
  town: string | null;
  phoneNumber: string | null;
  shippingStreet: string | null;
  shippingCity: string | null;
  shippingPostalCode: string | null;
  shippingCountry: string | null;
  visibleOnHiscores: boolean;
  visibleOnPeopleSearch: boolean;
  admin: boolean;
  country: string | null;
  platform: string | null;
  appVersion: string | null;
  lastLatitude: string | null;
  lastLongitude: string | null;
  lastLocationAt: Date | null;
  username: string | null;
  locale: string | null;
  activeChallengeId: string | null;
  unlockables: string[];
  createdAt: Date;
};
